openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Vocabulary
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Vocabulary
    description: Vocabulary service APIs

paths:
  /vocabulary:
    get:
      tags:
        - Vocabulary
      summary: Find vocabulary by type
      description: Returns vocabulary
      operationId: getVocabularyByType
      parameters:
        - name: type
          in: query
          description: vocabulary type like business/food/electronics
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Vocabulary'
            application/json:
              schema:
                $ref: '#/components/schemas/Vocabulary'
        '400':
          description: Invalid type supplied
        '404':
          description: Vocabulary not found
    post:
      tags:
        - Vocabulary
      summary: Add a new vocabulary
      description: ''
      operationId: addvocabulary
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Vocabulary'
            application/json:
              schema:
                $ref: '#/components/schemas/Vocabulary'
        '405':
          description: Invalid input
components:
  schemas:
    Vocabulary:
      type: array
      items:
        $ref: '#/components/schemas/word'
    word:
      title: a Vocabulary
      description: A Vocabulary
      type: object
      required:
        - word
        - meaning
      properties:
        word:
          type: string
        meaning:
          type: string
        sentence:
          type: string